# Generated by Django 4.1.2 on 2022-10-31 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advocates", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advocate",
            name="twitter",
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name="advocate",
            name="username",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
